Ajax
iwasawa15/Chatspace pull request #11
Opened 2019-02-10 19:37 UTC by iwasawa15

#WHAT
メッセージ送信での非同期通信の実装

#WHY
UXの向上

2019-02-12 10:48 UTC, ghost requested changes
連続で送信できないような気がするのですが、一度非同期で送った後にそのままの画面でもう一度送信できますか？

2019-02-12 10:48 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +  return false;
ここでfalseを返しているのはなぜですか？

2019-02-12 12:23 UTC, iwasawa15 commented on app/assets/javascripts/message.js
> +  return false;
submitの送信の処理を中断するためだと思ってました。

2019-02-12 12:36 UTC, iwasawa15 commented
一応送れます。
https://gyazo.com/c4a8bbec0964da4a61c027a5f00f96eb

2019-02-14 06:44 UTC, miyagit commented on app/assets/javascripts/message.js
> +      $('.text-field').val('')
form属性のresetメソッドを使いましょう。

2019-02-14 06:44 UTC, miyagit commented on app/assets/javascripts/message.js
> +      $('.upload-file').val('')
こちら不要になりますね。

2019-02-14 06:44 UTC, miyagit commented on app/assets/javascripts/message.js
> +  return false;
preventDefault()についてはどういう認識ですか？

2019-02-14 07:07 UTC, iwasawa15 commented on app/assets/javascripts/message.js
> +  return false;
preventDefaultもsubmitの動作をキャンセルするという認識でしたが、これだけだと連続して送信ボタンを押すことができないので、処理を止めてクリックを受け付けなくなるものなのかと考え、return falseを記述しました。

2019-02-14 07:37 UTC, iwasawa15 commented on app/assets/javascripts/message.js
> +      $('.text-field').val('')
修正しました。

2019-02-14 07:37 UTC, iwasawa15 commented on app/assets/javascripts/message.js
> +      $('.upload-file').val('')
resetを用いたため削除しました。

2019-02-14 07:38 UTC, yuki-uchida approved these changes

2019-02-14 07:38 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  function buildHTML(message){
buildHTMLでは、何をどうするのかがわかりづらいので、buildSendMessageHTMLとかいかがでしょうか

2019-02-14 07:38 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    .done(function(data){
dataでは、何を受け取ったのかわからないので、それがわかる名前に変えましょう

2019-02-14 07:45 UTC, iwasawa15 commented on app/assets/javascripts/message.js
> +  function buildHTML(message){
分かりやすいようにbuildSendMessageHTMLに変更しました。

2019-02-14 07:46 UTC, iwasawa15 commented on app/assets/javascripts/message.js
> +    .done(function(data){
送られてきているのはメッセージなのでmessageに変更しました。

2019-02-14 07:50 UTC, yuki-uchida approved these changes
LGTMです！

2019-02-14 07:51 UTC, merged