Incremental search
iwasawa15/Chatspace pull request #12
Opened 2019-02-11 15:59 UTC by iwasawa15

#WHAT
グループのメンバーを追加する際にチェックボックスからインクリメンタルサーチでメンバーを追加できるようにした。

#WHY
ユーザー数が多くなるとチェックボックスでは限界があるから。
インクリメンタルサーチの方が使い勝手が良いから。

2019-02-12 10:50 UTC, ghost requested changes

2019-02-12 10:50 UTC, hiroki5123 commented on app/controllers/users_controller.rb
> +      format.html
この記述不要かと思いますがいかがでしょうか？

2019-02-12 14:50 UTC, iwasawa15 commented on app/controllers/users_controller.rb
> +      format.html
format.htmlの1行ですよね？
削除しました。

2019-02-14 08:10 UTC, yuki-uchida requested changes

2019-02-14 08:10 UTC, yuki-uchida commented on app/assets/javascripts/index.js
> +    function appendUser(user) {
appendUserでは、何をどうするのかがわかりづらいので、appendSearchUserResultとかはいかがでしょうか

2019-02-14 08:16 UTC, iwasawa15 commented on app/assets/javascripts/index.js
> +    function appendUser(user) {
名前変更しました！

2019-02-14 08:23 UTC, TOMARUMARU approved these changes
LGTM

2019-02-14 08:24 UTC, merged